--- 
- name: crate a file with text
  hosts: node02
  gather_facts: true
  tasks: 
  - file: 
     path: /root/facts.txt
     state: touch
  - blockinfile:
     path: /root/facts.txt
     block: |
        This is Ansible managed node "{{ ansible_nodename }}"
        IP address of host is "{{ ansible_default_ipv4.address }}"
        Its OS family is "{{ ansible_os_family }}"
  - copy:
     src: /root/facts.txt
     dest: /usr/share/nginx/html/index.html
     remote_src: yes